"""Build the BGE-M3 embedding cache used by hierarchical source routing.

Input:
    ``routing_units.jsonl`` generated by ``scripts/build_rag_routing_index.py``
    for web sources or ``scripts/build_rag_pdf_index.py`` for PDF sources.

Routing units are coarse source identity, source catalog, section-window, and
structured-fact representations. Hierarchical retrieval scores these units
before ranking detailed evidence chunks. Their embeddings therefore live in a
separate cache from normal chunk embeddings.

This builder is cache-first. It reuses records whose route ID, BGE-M3 model,
and route-text hash still match, and embeds only missing or changed routes
unless ``--refresh`` is passed. BGE-M3 stores both dense and sparse route
representations; no OpenAI API is used by this script.

Build routing units before running this script. If routing units change, rebuild
this cache before using ``hierarchical-bge-m3-rrf``.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from src.rag.chunker import load_jsonl
from src.rag.embeddings import DEFAULT_BGE_M3_MODEL, ensure_embedding_cache
from src.rag.pdf_paths import PDF_ROUTING_EMBEDDINGS_PATH, PDF_ROUTING_UNITS_PATH
from src.rag.routing import DEFAULT_ROUTING_EMBEDDINGS_PATH, DEFAULT_ROUTING_UNITS_PATH


def build_parser() -> argparse.ArgumentParser:
    """Define routing-cache options for the web and PDF corpora."""
    parser = argparse.ArgumentParser(description="Build BGE-M3 embeddings for routing units.")
    parser.add_argument(
        "--source-set",
        choices=("web", "pdf"),
        default="web",
        help="Use default web or PDF-only routing paths.",
    )
    parser.add_argument(
        "--routing-units",
        default=str(PROJECT_ROOT / DEFAULT_ROUTING_UNITS_PATH),
        help=(
            "Input routing-unit JSONL. An explicit path overrides the default "
            "selected by --source-set."
        ),
    )
    parser.add_argument(
        "--embeddings",
        default=str(PROJECT_ROOT / DEFAULT_ROUTING_EMBEDDINGS_PATH),
        help=(
            "Output BGE-M3 routing embedding JSONL. An explicit path overrides "
            "the default selected by --source-set."
        ),
    )
    parser.add_argument(
        "--model",
        default=DEFAULT_BGE_M3_MODEL,
        help="BGE-M3 model name recorded in and used to validate the cache.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=16,
        help="Number of pending routing units embedded per local model batch.",
    )
    parser.add_argument(
        "--refresh",
        action="store_true",
        help="Recompute every route even when a matching cache record exists.",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()

    # Path precedence is explicit CLI path, then the selected source-set
    # defaults. Web and PDF routes/caches remain separate so their evidence
    # scopes cannot be mixed accidentally.
    routing_units = Path(args.routing_units)
    embeddings = Path(args.embeddings)
    defaults = build_parser()
    if args.source_set == "pdf" and args.routing_units == defaults.get_default("routing_units"):
        routing_units = PROJECT_ROOT / PDF_ROUTING_UNITS_PATH
    if args.source_set == "pdf" and args.embeddings == defaults.get_default("embeddings"):
        embeddings = PROJECT_ROOT / PDF_ROUTING_EMBEDDINGS_PATH

    # Each route exposes ``chunk_id`` and text fields compatible with the shared
    # embedding cache builder. Route IDs serve as embedding-record IDs.
    routes = load_jsonl(routing_units)

    # ensure_embedding_cache first counts complete records for the requested
    # BGE-M3 model and current route-text hashes. If every route is complete it
    # performs no model inference; otherwise it reuses valid records and embeds
    # only pending routes. ``--refresh`` forces all routes into the pending set.
    result = ensure_embedding_cache(
        routes,
        path=embeddings,
        provider="bge-m3",
        model=args.model,
        batch_size=args.batch_size,
        refresh=args.refresh,
    )

    # The reported pre-build count distinguishes a fully warm cache from a
    # partial/incremental rebuild and makes unexpected route churn visible.
    status = "built/updated" if result.built else "already complete"
    print(f"Routing embedding cache {status}: {result.path}")
    print(f"Embedding provider: {result.provider}")
    print(f"Embedding model: {result.model}")
    print(f"Routing units: {result.total_chunks}")
    print(f"Existing complete records before build: {result.existing_complete_records}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
